dock_station/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(('main.urls', "main"), namespace="main")),
]

main/urls.py
from django.urls import path
from django.contrib import admin
from . import views
admin.site.site_header = 'Bike sharing app manager panel'
admin.site.site_title = 'BikeApp admin'
admin.site.site_url = 'http://127.0.0.1:8000/'
admin.site.index_title = 'bikeapp administration'

app_name = "main"   


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("signin/", views.signin_request, name="signin"),
    path('logout/',views.logout_request, name='logout'),
    path("register/", views.register_request, name="register"),
    
    path('search/' , views.SearchView.as_view() , name="search"),
    path("bookings/<int:id>", views.BookingView.as_view(), name="bookings"),
    path("payment", views.Payment.as_view(), name="payment"),
    path("drop", views.DropBicycleView.as_view(), name="drop_bicycle"),



]

main/models.py
from asyncio.windows_events import NULL
import uuid
from django.db import models
from django.contrib.auth.models import User
import uuid

class UserOTP(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    time_st = models.DateTimeField(auto_now=True)
    otp = models.PositiveSmallIntegerField()


class BicycleData(models.Model):
    name = models.CharField(max_length=20,unique=True,null=True,blank=True)
    def __str__(self):
            return self.name

class DockStation(models.Model): 
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=200) 
    postcode = models.CharField(max_length=100) 
    landmark = models.TextField(blank=True)
    image = models.CharField(max_length=500,null=True)
    total_docks = models.IntegerField()
    bikes_availible = models.IntegerField()
    dropoff_docks = models.IntegerField()
    bicycle= models.ManyToManyField(BicycleData,related_name="dock_station_bicycle")
    latitude = models.DecimalField(max_digits=22, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=22, decimal_places=6, blank=True, null=True)

    def __str__(self):
        return self.name
    
class Booking(models.Model):
    booking_postcode = models.CharField(max_length=20)
    Charges =models.FloatField()
    booking_from=models.TextField()
    booking_to=models.TextField()
    booking_time = models.TimeField()
    leave_time=  models.TimeField()
    bicycle= models.CharField(max_length=20)
    email =  models.EmailField()
    user= models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    user_address = models.TextField()
    status = models.BooleanField(default=False)
    stripe_payment_intent =  models.CharField(max_length=255,null=True,blank=True)
    bicycle_drop_status =  models.BooleanField(default=False)
    booking_date = models.DateTimeField(auto_now_add=True, null=True)
    drop_datetime= models.DateTimeField(null=True)
    
    def __str__(self) -> str:
        return self.booking_postcode

main/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from .validators import validate_email,validate_username
from django import forms
class NewUserForm(UserCreationForm):
	username = forms.CharField(max_length=100,validators=[validate_username],
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
	email = forms.EmailField(required=True,validators = [validate_email],
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
	password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
	password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  'label':'Confirm Password',
                                                                  }))
	class Meta:
        
		model = User
		fields = ['username', 'email', 'password1', 'password2']
	
	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user 
	
class AuthenticationForm(AuthenticationForm):
	username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
	password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
	
	
	class Meta:
		model = User
		fields = ['username', 'password']


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    subject = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Subject',
                                                           'class': 'form-control',
                                                           }))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Type in your message',
                                                           'class': 'form-control',
                                                           }), required=True)

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import  render, redirect
from .forms import NewUserForm,AuthenticationForm
from django.contrib.auth import login, authenticate,logout
from django.conf import settings
from django.views.decorators.csrf import csrf_protect
from django.core.mail import send_mail
from django.contrib.auth.models import User
from .models import DockStation,UserOTP
from django.core.mail import send_mail
from django.contrib import messages
from django.views import generic
from django.db.models.functions import Radians, Power, Sin, Cos, ATan2, Sqrt, Radians
from django.db.models import F
from datetime import datetime
from .models import Booking
import stripe
from dock_station import settings
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register

now = datetime.now()
current_time = now.strftime("%H:%M")
# Create your views here.

@csrf_protect
def homepage(request):

	return render(request, 'main/home.html') 


@csrf_protect
def register_request(request):
	if request.method == 'POST':
		get_otp = request.POST.get('otp') #213243 #None
		if get_otp:
			get_usr = request.POST.get('usr')
			usr = User.objects.get(username=get_usr)
			if int(get_otp) == UserOTP.objects.filter(user = usr).last().otp:
				usr.is_active = True
				usr.save()
				messages.success(request, f'Account is Created For {usr.username}')
				return redirect('main:signin')
			else:
				messages.warning(request, f'You Entered a Wrong OTP')
				return render(request, 'main/register.html', {'otp': True, 'usr': usr})
		form = NewUserForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			usr = User.objects.get(username=username)
			usr.email = email
			usr.username = username
			usr.is_active = False
			usr.save()
			usr_otp = random.randint(100000, 999999)
			UserOTP.objects.create(user = usr, otp = usr_otp)
			message = f"Hello {usr.username}\n\nTo authenticate, please enter the following one time password:\n {usr_otp} \n Thanks!"
			send_mail(
				"Welcome to Bikers Hub - Verify Your Email",
				message,
				settings.EMAIL_HOST_USER,
				[usr.email],
				fail_silently = False
				)
			return render(request, 'main/register.html', {'otp': True, 'usr': usr})		

	else:
		form = NewUserForm()
	return render(request, 'main/register.html', {'register_form':form})



@csrf_protect
def signin_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="main/signin.html", context={"login_form":form})


@csrf_protect
@method_decorator(login_required(login_url='/'), name='dispatch')
def logout_request(request):
    logout(request)
    messages.success(request, "Successfully logged out")
    return redirect("main:homepage")


@method_decorator(login_required(login_url='/'), name='dispatch')
class SearchView(generic.ListView):
	template_name = 'main/postcodesearch.html'
	context_object_name='dock_stations'
	
	def get_queryset(self):
		query= DockStation.objects.all()
		if self.request.GET.get('postalcode') and self.request.GET.get('dis'):
			instance = DockStation.objects.get(postcode=self.request.GET.get('postalcode'))
			dlat = Radians(F('latitude') - instance.latitude)
			dlong = Radians(F('longitude') -instance.longitude)

			a = (Power(Sin(dlat / 2), 2) + Cos(Radians(instance.latitude)) * Cos(Radians(F('latitude'))) * Power(Sin(dlong / 2), 2))

			c = 2 * ATan2(Sqrt(a), Sqrt(1 - a))
			d = 6371 * c
			query=query.annotate(distance = d).order_by('distance').filter(distance__lt =self.request.GET.get('dis'))

		return query

	def get_context_data(self, **kwargs) :
		context=super().get_context_data(**kwargs)
		context['postalcode'] =self.request.GET.get('postalcode')
		context['dis'] = int(self.request.GET.get('dis',1))
		context['distance'] = [1,2,3,4,5,6,7,8,9,10]
		return context
	
@method_decorator(login_required(login_url='/'), name='dispatch')	
class BookingView(generic.TemplateView):
	template_name = 'main/bookings.html'

	def get(self,request,id):
		instance=DockStation.objects.get(id=id)
		address= DockStation.objects.values_list('address',flat=True)
		
		bicycle=instance.bicycle.first()
		return render(request,self.template_name,{'current_time':current_time,
      'instance':instance,'address':address,'bicycle':bicycle})

@method_decorator(login_required(login_url='/'), name='dispatch')
class Payment(generic.View):
      
		def post(self, request, *args, **kwargs): 
			address = request.POST.get('address')
			email = request.POST.get('email')
			booking_to = request.POST.get('booking_to')
			leave_time = request.POST.get('leave_time')
			station_id = request.POST.get('station_id')
			station=DockStation.objects.get(id=station_id)
			booking=Booking(booking_postcode=station.postcode,Charges=120,booking_from=station.address,
                         booking_to=booking_to,booking_time=current_time,leave_time=leave_time,email=email,
                         user_address=address,user=request.user )
		
			stripe.api_key = settings.STRIPE_SECRET_KEY
			checkout_session = stripe.checkout.Session.create(
			           customer_email = email,
                payment_method_types=['card'],
                line_items=[
                    {
                        'price_data': {
                            'currency': 'inr',
                            'product_data': {
                            'name':'Plan ',
                            },
                            'unit_amount': int((120)*100),
                        },
                        'quantity': 1,
                    }
                ],
                mode='payment',
				success_url=request.build_absolute_uri(reverse('main:search') ) + "?session_id={CHECKOUT_SESSION_ID}",
				cancel_url=request.build_absolute_uri(reverse('main:search')),
				) 
			booking.stripe_payment_intent=checkout_session["payment_intent"]
			booking.status=True
			booking.bicycle=station.bicycle.first()
			station.bicycle.remove(station.bicycle.first())
			booking.save()
			
				
			return redirect(checkout_session["url"])

    #Testing card number
    
#     NUMBER         BRAND                            CVC   
# 4242424242424242	Visa	                    Any 3 digits	
# 4000056655665556	Visa (debit)	            Any 3 digits	
# 5555555555554444	Mastercard	                Any 3 digits	
# 2223003122003222	Mastercard (2-series)	    Any 3 digits	
# 5105105105105100	Mastercard (prepaid)	    Any 3 digits	
# 378282246310005	    American Express	         Any 4 digits
# 371449635398431	    American Express	        Any 4 digits
# 6011111111111117	Discover	                Any 3 digits	
# 6011000990139424	Discover	                Any 3 digits	
# 3056930009020004	Diners Club	                Any 3 digits	
# 36227206271667	     Diners Club(14 digit card) Any 3 digits	
# 3566002020360505	JCB	                       Any 3 digits	
# 6200000000000005	UnionPay	                Any 3 digits	


@register.filter(name='check_booking_status')
def check_booking_status(user):
    status = False
    if Booking.objects.filter(bicycle_drop_status=False).filter(user=user).exists():
        status =True
    return status

@register.filter(name='booking_id')
def booking_id(user):
    if Booking.objects.filter(bicycle_drop_status=False).filter(user=user).exists():
        ins=Booking.objects.get(bicycle_drop_status=False,user=user)
    return ins.id

@method_decorator(login_required(login_url='/'), name='dispatch')	
class DropBicycleView(generic.TemplateView):
	template_name = 'main/drop-bicycle.html'

	def get(self,request):
	
		instance=Booking.objects.get(id=request.GET.get('id'))
		address= DockStation.objects.values_list('address',flat=True)
		return render(request,self.template_name,{'now':now,'current_time':current_time,'instance':instance,'address':address})

	def post(self,request):
		instance=Booking.objects.get(id=request.GET.get('id'))
		booking_to=request.POST.get('booking_to')
		instance.booking_to=booking_to
		instance.bicycle_drop_status = True
		instance.drop_datetime = now
		instance.save()
		station=DockStation.objects.get(address=booking_to)
		bicycle = [data.id for data in station.bicycle.all()]
		bicycle.append(station.id)
		station.bicycle.set(bicycle)
		messages.success(request,f'Bicycle successfully dropped at {booking_to}')
		return HttpResponseRedirect(reverse('main:search'))

main/templates/main/bookings.html
{% extends "main/home.html" %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Bikers Den</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block contactactive %}  {% endblock contactactive %} ">
                <a class="nav-link" href="/contact">Contact Us</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/bookings">Booking History</a>
            </li>
            {% endif %}
        </ul>
    </div>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="btn btn-outline-success m-2 my-sm-0" href="/logout">Logout as {{user.username}} </a>
    </li>
    {% endif %}
    </div>
</nav>
<div id="app">
    <div class="container">
        <form method="POST" action="{% url 'main:payment' %}">
            {% csrf_token %}
            {% comment %} <div>
                <h5>{{instance.name}}</h5></br>
            </div> {% endcomment %}
            <div class="row mt-5 pt-5">
                <div class="col-md-6">
                    <label>Post Code</label>
                    <input class="form-control" readonly value="{{instance.postcode}}" type="text" required>
                </div>
                <div class="col-md-6">
                    <label>Charges</label>
                    <input class="form-control" readonly type="text" value="120 rupees/day" required>
                </div>
                <div class="col-md-6">
                    <label>From</label>
                    <input class="form-control" readonly type="text" value="{{instance.address}}" required>
                </div>
                <div class="col-md-6">
                    <label>To</label>
                    <select class="form-control" v-model="mile_radius" required name="booking_to">
                        {% for data in address %}
                        <option>{{data}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6">
                    <label>Book Time</label>
                    <input class="form-control" type="time" value="{{current_time}}" name="postalcode" placeholder="Enter Posctode" required>
                </div>
                <div class="col-md-6">
                    <label>Check out Time </label>
                    <input class="form-control" type="time" name="leave_time" required>
                </div>
                <div class="col-md-6">
                    <label>Bicycle</label>
                    <input class="form-control" type="text" readonly value="{{bicycle}}" placeholder="name" required>
                </div>
                <div class="col-md-6">
                    <label>Name</label>
                    <input class="form-control" type="text" readonly value="{{request.user.username}}" placeholder="name" required>
                </div>
                <div class="col-md-6">
                    <label>Email</label>
                    <input class="form-control" type="email" name="email" value="{{request.user.email}}" required>
                </div>
                <div class="col-md-6">
                    <label>Permanent Address</label>
                    <textarea row="1" class="form-control" type="text" name="address" placeholder="address" required></textarea>
                </div>
                <input type="hidden" name="station_id" value="{{instance.id}}">
                <div class="col-md-6" style="margin-left: 72px;"> 
                    <button class="btn btn-primary mt-4" style="float: right;">Continue & Pay</button>
                </div>
                <p>Note:-Please drop bicycle on time otherwise team will contact you or may be take action.</p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/drop-bicycle.html
{% extends "main/home.html" %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Bikers Den</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block contactactive %}  {% endblock contactactive %} ">
                <a class="nav-link" href="/contact">Contact Us</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/bookings">Booking History</a>
            </li>
               {% if request.user|check_booking_status %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:drop_bicycle'  %}?id={{request.user|booking_id}}">Drop Bicycle</a>
            </li> 
            {% endif %}
                 {% endif %} 
        </ul>
    </div>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="btn btn-outline-success m-2 my-sm-0" href="/logout">Logout as {{user.username}} </a>
    </li>
    {% endif %}
    </div>
</nav>
<div id="app">
    <div class="container">
        <form method="POST" action="{% url 'main:drop_bicycle' %}?id={{instance.id}}">
            {% csrf_token %}
            {% comment %} <div>
                <h5>{{instance.name}}</h5></br>
            </div> {% endcomment %}
            <div class="row mt-5 pt-5">
                <div class="col-md-6">
                    <label>Booking Post Code</label>
                    <input class="form-control" readonly value="{{instance.booking_postcode}}" type="text" required>
                </div>
                <div class="col-md-6">
                    <label>Paid Charges</label>
                    <input class="form-control" readonly type="text" value="120 rupees/day" required>
                </div>
                <div class="col-md-6">
                    <label>Booking From</label>
                    <input class="form-control" readonly type="text" value="{{instance.booking_from}}" required>
                </div>
                <div class="col-md-6">
                    <label>Drop station</label>
                    <select class="form-control" v-model="mile_radius" required name="booking_to">
                        {% for data in address %}
                        {% if data == instance.booking_to %}
                        <option selected>{{data}}</option>
                        {% else %}
                          <option >{{data}}</option>
                          {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-6">
                    <label>Booking DateTime</label>
                    <input class="form-control" type="text" readonly value="{{instance.booking_date}}" name="postalcode" placeholder="Enter Posctode" required>
                </div>
                <div class="col-md-6">
                    <label>Check out Time(current) </label>
                    <input class="form-control" type="text" readonly value="{{now}}" name="leave_time" required>
                </div>
                <div class="col-md-6">
                    <label>Bicycle</label>
                    <input class="form-control" type="text" readonly value="{{instance.bicycle}}" placeholder="name" required>
                </div>
          
                <input type="hidden" name="station_id" value="{{instance.id}}">
                <div class="col-md-6" style="margin-left: 72px;"> 
                    <button class="btn btn-primary mt-4" style="float: right;">Drop Here</button>
                </div>
                
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/postcodesearch.html
{% extends "main/home.html" %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Bikers Den</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block contactactive %}  {% endblock contactactive %} ">
                <a class="nav-link" href="/contact">Contact Us</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/bookings">Booking History</a>
            </li>
                {% if request.user|check_booking_status %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:drop_bicycle'  %}?id={{request.user|booking_id}}">Drop Bicycle</a>
            </li> 
            {% endif %}
            {% endif %}
        </ul>
    </div>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="btn btn-outline-success m-2 my-sm-0" href="/logout">Logout as {{user.username}} </a>
    </li>
    {% endif %}
    </div>
</nav>
<div id="app">
    <div class="container">
          <form method="GET">
        <div class="row mt-5 pt-5">
          
            <div class="col-md-4">
                <label>Enter Postcode</label>
                <input class="form-control" type="text" value="{{postalcode|default:''}}" name="postalcode" placeholder="Enter Posctode" required>
            </div>
            <div class="col-md-4">
                <label>Select Mile Radius</label>
                <select class="form-control" v-model="mile_radius" required name="dis">
                   {% for data in distance %}
                   {% if data == dis %}
                    <option value="{{data}}" selected>{{data}} Mile(Approx)</option>
                    {% else %}
                    <option value="{{data}}">{{data}} Miles(Approx)</option>
                    {% endif %}
                    {% endfor %}
                  
                </select>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary mt-4" >Search</button>
            </div>
      
        </div>
          </form>
        <div class="container">
            <div class="row mt-5 pt-5">
                {% for data in dock_stations %}
                <div class="col-sm col-xs-4" v-for="dockstation in dockstations"><br>
                    <div class="card" style="width: 18rem;">
                        <img src="{{data.image}}" class="card-img-top" style="height:200px">
                        <div class="card-body">
                            <h5 class="card-title">{{data.name}} </h5>
                            <p class="card-text">{{data.landmark}} </p>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% if dockstation.distance %}
                            <li class="list-group-item"><strong>{{dockstation.distance}} Miles Away!</strong></li>
                            {% endif %}
                            <li class="list-group-item">Address:-{{data.address}} </li>
                            <li class="list-group-item">PostCode:-{{data.postcode}} </li>
                               <li class="list-group-item">{{data.bicycle.count}} available</li>
                        </ul>
                        <div class="card-body">
                         {% if request.user|check_booking_status %}
                            <a href="javascript:void(0)" onclick="dropoff()" class="btn btn-primary" style="margin-left: 64px;">Book Now</a>
                            {% else %}
                            <a href="{% url 'main:bookings' data.id %}" class="btn btn-primary" style="margin-left: 64px;">Book Now</a>
                        {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<br><br>
  <script>
    
    function dropoff(){
      alert("Drop off first for next booking")
    }
  </script>
<!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<script>
    const app = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data() {
            return {
                postcode : '',
                mile_radius : '',
                tasks: [],
                dockstations : []
            }
        },
        
        created() {
            this.tasks = ['do this 🐱‍🐉', 'and that 🤳'];
        },
        methods : {
            getRest(){         
                fetch(`/search/get/?postcode=${this.postcode}&mile_radius=${this.mile_radius}`)
                .then(result => result.json())
                .then(response => {
                    this.dockstations = response
                })
            }
        }
    });
</script> -->
{% endblock %}

main/templates/main/signin.html
{% extends "main/home.html" %}
{% csrf_token %}
{% block content %} 
{% load crispy_forms_tags %}       

<!--Login--> 
<div class="container py-5" id="loginModal">
<br>
<h1>Login</h1>
<form method="POST">{% csrf_token %}
  {{ login_form|crispy }}
  <button class="btn btn-primary" type="submit">Login</button>
</form>
<p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
<p class="text-center">Forgotten your password? <a href="/password_reset">Forgot Password</a></p>
</div>

{% endblock %}